/* Generated by Foundation tools/ffi_header.py; do not edit. */
#ifndef MEDIA_BACKUP_FFI_V2_H
#define MEDIA_BACKUP_FFI_V2_H
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

#define SARMG_FFI_ABI_REVISION 2u
#define SARMG_FFI_MAX_INPUT_BYTES 16777216u
#define SARMG_FFI_MAX_OUTPUT_BYTES 16777216u
#define SARMG_FFI_MAX_HANDLES 4096u
#define SARMG_FFI_OK 0u
#define SARMG_FFI_INVALID_ARGUMENT 1u
#define SARMG_FFI_INVALID_HANDLE 2u
#define SARMG_FFI_INTERNAL_ERROR 3u
#define SARMG_FFI_RESOURCE_EXHAUSTED 4u
#define SARMG_FFI_INTERNAL_PANIC 255u

typedef struct SarmgFfiBytesV2 {
    uint8_t * data;
    size_t length;
} SarmgFfiBytesV2;
typedef struct SarmgFfiResultV2 {
    uint32_t abi_revision;
    int32_t status;
    uint64_t value;
    SarmgFfiBytesV2 bytes;
} SarmgFfiResultV2;

/* Inputs are borrowed for the call. Output must be aligned, writable, and
 * not alias input or contain an unreleased result. Status is authoritative.
 * Free each result in its original storage with sarmg_ffi_result_free_v2;
 * do not copy, modify, or separately free its pointer/length pair. */
int32_t sarmg_ffi_result_free_v2(SarmgFfiResultV2 * output);
int32_t mb_transfer_v2(uint64_t handle, const uint8_t * input, size_t input_len, SarmgFfiResultV2 * output);
uint32_t mb_ffi_abi_revision(void);
int32_t mb_open_v2(const uint8_t * path, size_t path_len, const uint8_t * config, size_t config_len, SarmgFfiResultV2 * output);
int32_t mb_close_v2(uint64_t handle, SarmgFfiResultV2 * output);
int32_t mb_needs_v2(uint64_t handle, const uint8_t * asset, size_t asset_len, const uint8_t * resource, size_t resource_len, int64_t modified_ms, SarmgFfiResultV2 * output);
int32_t mb_enqueue_v2(uint64_t handle, const uint8_t * input, size_t input_len, SarmgFfiResultV2 * output);
int32_t mb_next_v2(uint64_t handle, const uint8_t * staging, size_t staging_len, SarmgFfiResultV2 * output);
int32_t mb_mark_upload_v2(uint64_t handle, const uint8_t * job, size_t job_len, const uint8_t * upload, size_t upload_len, SarmgFfiResultV2 * output);
int32_t mb_mark_part_v2(uint64_t handle, const uint8_t * job, size_t job_len, uint32_t index, SarmgFfiResultV2 * output);
int32_t mb_mark_complete_v2(uint64_t handle, const uint8_t * job, size_t job_len, SarmgFfiResultV2 * output);
int32_t mb_mark_failed_v2(uint64_t handle, const uint8_t * job, size_t job_len, const uint8_t * message, size_t message_len, uint8_t retryable, SarmgFfiResultV2 * output);
int32_t mb_stats_v2(uint64_t handle, SarmgFfiResultV2 * output);

#ifdef __cplusplus
}
#endif
#endif /* MEDIA_BACKUP_FFI_V2_H */
