/* Generated by Foundation tools/ffi_header.py; do not edit. */
#ifndef XSZC_FFI_V1_H
#define XSZC_FFI_V1_H
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

#define XCSC_FFI_ABI_REVISION 1u
#define XCSC_FFI_MAX_INPUT_BYTES 16777216u
#define XCSC_FFI_MAX_OUTPUT_BYTES 16777216u
#define XCSC_FFI_MAX_HANDLES 4096u
#define XCSC_FFI_OK 0u
#define XCSC_FFI_INVALID_ARGUMENT 1u
#define XCSC_FFI_INVALID_HANDLE 2u
#define XCSC_FFI_INTERNAL_ERROR 3u
#define XCSC_FFI_RESOURCE_EXHAUSTED 4u
#define XCSC_FFI_INTERNAL_PANIC 255u

typedef struct XcscFfiBytesV1 {
    uint8_t * data;
    size_t length;
} XcscFfiBytesV1;
typedef struct XcscFfiResultV1 {
    uint32_t abi_revision;
    int32_t status;
    uint64_t value;
    XcscFfiBytesV1 bytes;
} XcscFfiResultV1;

/* Inputs are borrowed for the call. Output must be aligned, writable, and
 * not alias input or contain an unreleased result. Status is authoritative.
 * Free each result in its original storage with xcsc_ffi_result_free_v1;
 * do not copy, modify, or separately free its pointer/length pair. */
int32_t xcsc_ffi_result_free_v1(XcscFfiResultV1 * output);
int32_t xszc_transfer_v1(uint64_t handle, const uint8_t * input, size_t input_len, XcscFfiResultV1 * output);
uint32_t xszc_ffi_abi_revision(void);
int32_t xszc_open_v1(const uint8_t * path, size_t path_len, const uint8_t * config, size_t config_len, XcscFfiResultV1 * output);
int32_t xszc_close_v1(uint64_t handle, XcscFfiResultV1 * output);
int32_t xszc_needs_v1(uint64_t handle, const uint8_t * asset, size_t asset_len, const uint8_t * resource, size_t resource_len, int64_t modified_ms, XcscFfiResultV1 * output);
int32_t xszc_verify_file_blake3_v1(const uint8_t * path, size_t path_len, uint64_t expected_size, const uint8_t * expected_hash, size_t expected_hash_len, XcscFfiResultV1 * output);
int32_t xszc_enqueue_v1(uint64_t handle, const uint8_t * input, size_t input_len, XcscFfiResultV1 * output);
int32_t xszc_next_v1(uint64_t handle, const uint8_t * staging, size_t staging_len, XcscFfiResultV1 * output);
int32_t xszc_mark_upload_v1(uint64_t handle, const uint8_t * job, size_t job_len, const uint8_t * upload, size_t upload_len, XcscFfiResultV1 * output);
int32_t xszc_mark_part_v1(uint64_t handle, const uint8_t * job, size_t job_len, uint32_t index, XcscFfiResultV1 * output);
int32_t xszc_mark_complete_v1(uint64_t handle, const uint8_t * job, size_t job_len, XcscFfiResultV1 * output);
int32_t xszc_mark_failed_v1(uint64_t handle, const uint8_t * job, size_t job_len, const uint8_t * message, size_t message_len, uint8_t retryable, XcscFfiResultV1 * output);
int32_t xszc_stats_v1(uint64_t handle, XcscFfiResultV1 * output);

#ifdef __cplusplus
}
#endif
#endif /* XSZC_FFI_V1_H */
