[package]
name = "xszc-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
xszc-crypto = { path = "../crypto" }
xszs-protocol = { git = "https://github.com/isarmg/xszs.git", rev = "ad2688c00c9fb9df4e137399f4a02fee858742a7", version = "=1.0.0" }
xcsc-fs-safety = { git = "https://github.com/isarmg/xcsc.git", rev = "a3c827b7f0f69d84ff69f72be1533a7171ab63d6", version = "=1.0.0" }
xcsc-runtime = { git = "https://github.com/isarmg/xcsc.git", rev = "a3c827b7f0f69d84ff69f72be1533a7171ab63d6", version = "=1.0.0" }
sqlx.workspace = true
futures-util.workspace = true
libsqlite3-sys.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
blake3.workspace = true
tokio.workspace = true

[lints]
workspace = true
