[package]
name = "xszc-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
xszc-crypto = { path = "../crypto" }
xszs-protocol = { git = "https://github.com/isarmg/xszs.git", rev = "c0aa705df39d3187166f62af4faab7c821be9baa", version = "=1.0.0" }
xcsc = { git = "https://github.com/isarmg/xcsc.git", rev = "c45e48e93e360542c2e1db6c6441a9e29b344b03", version = "=1.0.0" }
sqlx.workspace = true
futures-util.workspace = true
libsqlite3-sys.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
blake3.workspace = true
tokio.workspace = true

[lints]
workspace = true
