[package]
name = "xszc-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
xszs-protocol = { git = "https://github.com/isarmg/xszs.git", rev = "c0aa705df39d3187166f62af4faab7c821be9baa", version = "=1.0.0" }
thiserror.workspace = true

[lints]
workspace = true
