[package]
name = "xszc-mobile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
xszc-core = { path = "../client-core" }
xszc-crypto = { path = "../crypto" }
serde_json.workspace = true
xcsc = { git = "https://github.com/isarmg/xcsc.git", rev = "00770c007912b276f5bb1075abfefe3c31026276", version = "=1.0.0", features = ["mobile-ffi"] }
jni = { workspace = true, optional = true }

[features]
jni-host-tests = ["dep:jni", "xcsc/jni"]

[target.'cfg(target_os = "android")'.dependencies]
jni.workspace = true
xcsc = { git = "https://github.com/isarmg/xcsc.git", rev = "00770c007912b276f5bb1075abfefe3c31026276", version = "=1.0.0", features = ["jni", "mobile-ffi"] }

[dev-dependencies]
jni.workspace = true
xcsc = { git = "https://github.com/isarmg/xcsc.git", rev = "00770c007912b276f5bb1075abfefe3c31026276", version = "=1.0.0", features = ["jni", "mobile-ffi"] }
tempfile.workspace = true

[lints]
workspace = true
