[package]
name = "media-backup-mobile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
media-backup-client-core = { path = "../client-core" }
serde_json.workspace = true
sarmg-mobile-ffi = { git = "https://github.com/isarmg/sarmg-foundation-client.git", rev = "b47b550a39336b4a592ea9acf26e98b4d8a660b1", version = "=0.7.0" }
jni = { workspace = true, optional = true }

[features]
jni-host-tests = ["dep:jni", "sarmg-mobile-ffi/jni"]

[target.'cfg(target_os = "android")'.dependencies]
jni.workspace = true
sarmg-mobile-ffi = { git = "https://github.com/isarmg/sarmg-foundation-client.git", rev = "b47b550a39336b4a592ea9acf26e98b4d8a660b1", features = ["jni"], version = "=0.7.0" }

[dev-dependencies]
jni.workspace = true
sarmg-mobile-ffi = { git = "https://github.com/isarmg/sarmg-foundation-client.git", rev = "b47b550a39336b4a592ea9acf26e98b4d8a660b1", features = ["jni"], version = "=0.7.0" }
tempfile.workspace = true
